#!/data/data/com.termux/files/usr/bin/bash

# Parametre kontrolü
if [ -z "$1" ]; then
    echo "Kullanım: protokol <protokol kodu>"
    exit 1
fi

case "$1" in
    999)
        true_pw="Password"
        trap '' SIGINT
	echo -n "Şifreyi gir: "
	read entry_pw
	if [ "$entry_pw" == "$true_pw" ]; then
	    cd $HOME
	    clear
	    trap - SIGINT
	    neofetch
	    echo "Şifreniz Doğru!"
	    echo "Hoşgeldiniz RJC@localhost"

	else
	    protokol 998
	fi
        ;;
    998)
	cd $HOME
	clear
	echo "Şifre Yanlış!"
	tusername="TerUN"
	true_pw="Password"
	echo -n "Şifreyi Gir: "
	read entry_pw
	if [ "$entry_pw" == "$true_pw" ]; then
            cd $HOME
            clear
	    trap - SIGINT
            neofetch
            echo "Şifreniz Doğru!"
            echo "Hoşgeldiniz "$tusername"@localhost"

        else
            protokol 998
       fi
       ;;
    
    *)
        echo "Bilinmeyen protokol: $1"
        ;;
esac
